### ISSUE TITLE
screen/payment-screen

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#26]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/677f6ce8-14bc-4bd0-8e0a-774aa785637e)

yang saya kasih silang jangan buat dulu ya man, soalnya kemaren kata BE katanya gak mungkin buat payment ateway yang pake kartu debit dan kredit gitu

**Comment by michaelis2101** [comment]
buat tempat peyimpanan file nya buat folder baru aja di screen buat nyimpen file screen payment nya ya man, buat penamaan file nya itu sesuain aja sama konteks fungsi layarnya kek 'payment_screen.dart' terus 'payment_success.dart' gitu ya man

**Comment by itsMallix** [comment]
Siapp mas hafidz👍

**Comment by michaelis2101** [comment]
yang saya kasih silang jangan buat dulu ya man, soalnya kemaren kata BE katanya gak mungkin buat payment ateway yang pake kartu debit dan kredit gitu
