### ISSUE TITLE
screen/verifikasi-identitas

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#32]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/e81ed9dd-e607-4306-a1e8-a19ac077bcb6)

**Comment by omeralvin** [comment]
apa ini hanya UI sampai navigation aja berarti ya ?
@michaelis2101

**Comment by michaelis2101** [comment]
iyak vin, uinya aja, nanti logicnya aku aja yang ngerjain
