### ISSUE TITLE
fix/dashboard-appbar

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#43]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/d1d520c4-29b0-4f8e-b9ba-777aa1a91b2d)

tolong ubah appbar sama textfield search nya doang yak man, yang lain jangan ubah dulu

**Comment by itsMallix** [comment]
![Image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/477b12c8-640d-4793-81b8-e64bf50c789d)

Oke mas hafidz

**Comment by michaelis2101** [comment]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/eb7d2e8a-4372-4b04-8eb5-2e052396a7a9)
