### ISSUE TITLE
screen/set-location

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#44]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/52bcb142-f3f0-4f7a-a185-a87b0059ef3f)

vin, buat list kotanya silahkan import dari file city_collection.dart yang nama listnya itu kotaList yang mulai dari line 132 yang ini, bukan yang atasnya soalnya yang atasnya itu buat dropdown di layar auth

![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/bdb9008c-40f9-4f76-898d-530663fd3100)

**Comment by omeralvin** [comment]
oke di coba
