### ISSUE TITLE
fix/dashboard

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#53]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/bf33c417-9351-487e-a78f-4eceb3d555b4)

man yang background cardnya tolong ubah jadi warna putih yak :", udah ready to develop ternyata di figma gak liat aku tadi :"

**Comment by itsMallix** [comment]
<img src="https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/2e676294-5e06-4c66-8448-568a1aaf04ee" width="30%">

oke mas nanti malem selsai :v

**Comment by michaelis2101** [comment]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/962b90cd-23c0-4201-a4e2-f2780e6f1acb)
