### ISSUE TITLE
screen/botom-sheet-filter

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#57]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/4df83810-3549-4c62-84ac-1f93a71bfba0)

man tolong hapus beberapa field di versi lama yak, jadi samain aja kayak yang terbaru, sama kalo bisa si bottomsheetnya pindahin ke folder component yak

**Comment by itsMallix** [comment]
![Image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/fff197c6-5cf6-475c-b448-42addc4b9175)

buat screen search_result sama list_rec/loaction itu udah di slicing juga blom?, kalo belum apa di slicing juga skalian ?

**Comment by michaelis2101** [comment]
yang search itu belom sih, kalo yang rekomendasi udah man, boleh deh sekalian aja, buat card nya copas aja dari file yang screen favorite :"

**Comment by itsMallix** [comment]
Oke dah tak kerjain skalian :v
