### ISSUE TITLE
feat: detail-warehouse

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#68]
vin kita mulai ngerjain key activities kamu dulu yak jadi tolong buat logicnya buat nampilin warehouse yang dipilih ke screen yang detail warehouse yak, udah bisa dibuat harusnya karena fitur buat nyari warehouse lewat seacrh udah aku kerjain. di halaman search_screen.dart nanti kalo udah jadi fungsinya bisa di tempel disini yak file search_screen.dart

![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/67098f92-9a05-4beb-a06d-4658081d8bcf)

buat endpointnya ini : $baseurl/warehouse/detail/$ini-id-dari-warehouse-yang-dipilih
method endpoint nya GET, jadi gak perlu buat body apa apa buat fungsinya
status code nya: 
200 : success

selain itu masukin Get.snackbar aja si status code sama messagenya

terus si response dari API nya itu kayak gini

![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/657fdae8-b3b3-400c-af37-02c4d23eb292)

terus tolong masukin si token nya ke header yak, si tokennya udah urg simpen di sharedpreferences pas user login, jadi kamu daftar buat akun baru aja terus login nanti si tokennya bakalan ke simpen di sharepreferences, buat cara ngambil tokennya kayak gini yak

![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/7800c1ef-01ca-4a7c-b8d7-48b8091ad23f)

nanti simpen di header kayak gini
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/c1026d5b-0937-4688-ba92-24fce855447a)

terus buat fungsi get warehouse by id nya tolong simpen di file warehouse_services.dart yak, oh iyak sama nanti pas pindah layarnya tolong pake Get.to(()=> NamaScreen()) yang jangan pake navigator, biar kita bisa pasang transisinya, sama satu lagi buat url di response nya itu dummy, jadi nanti tolong buat aja dulu statis pake url gambar yang ada. kalo ada yang gak paham di pc atau grup whatsapp aja yak, awkoakw aing banyak request njir 🏃‍♂️

**Comment by omeralvin** [comment]
Menarik wkwk.. Gw coba buat dulu

**Comment by michaelis2101** [comment]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/0866fa80-43b0-4219-9b12-65cd3cfaf0ef)
