### ISSUE TITLE
fix: payment-screen

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#71]
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/fdc337fa-48b7-46af-a2d9-d85d2063945d)

man, kemarin itu ada beberapa payment method yang di hapus jadi tolong hapus juga yak man di dkodingannya :"),

sama kalo bisa sekalian tolong buatin screen yang buat virtual account itu yak :", sama buat background dan asset asset nya import aja SVG nya dari figma yak man. maap kebanyakan request gw :"v

**Comment by itsMallix** [comment]
wqwq oke mas gapapa kok amann😁👍

**Comment by itsMallix** [comment]
![Image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/9acd8567-1472-4b17-9e76-e75cfb72069a)

yang ini perlu juga nggak?

**Comment by michaelis2101** [comment]
jangan dulu man, kemungkinan kita gak akan pake transfer itu

**Comment by itsMallix** [comment]
<img src ="https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/5bb75a12-0bd5-470e-ac0a-7d78a3a825b0" width="40%">
