### ISSUE TITLE
feat/interactive-map

### ISSUE THREAD

**Issue by michaelis2101** [Capstone-Tim-12/warehouse-management-system-mobile#77]
man tolong buat yang interactive mapnya yak, buat latitude sama logintude nya itu bisa dipassing dari screen detail screen pake kek gini 
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/9109997a-6f8e-42dd-bc00-bb7731b64107)

jadi nanti paling kamu buat konsruktor aja di screen mapnya terus masukin warehouseData!['longitude'] sama warehouseData!['latitude'] keparameternya, buat response dari detail screennya itu kayak gini

![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/40931bc5-9fde-4c56-bf38-7fa379cac787)

terus buat di screen detail screen itu kan ada map kecilnya gitu, nah itu juga kalo bisa tolong tambahin yak kalo bisa tapi fokus yang screen yang full satu map itu aja dulu:" buat tempat mapnya udah ditandain sama alvin di detail screen itu ada container warna kuning, kalo gak bisa hapus aja containernya jadi cuman ada button lokasi doang :"

![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/46704b98-0eaf-4583-a7ba-e182354e1d9b)

terus buat file map screennya simpen di folder detail_gudang aja yak :"

**Comment by itsMallix** [comment]
Okee mas, siapp👍

**Comment by itsMallix** [comment]
Oh iya, mau mastiin aja se, berarti screen map ini cuma lihat lokasi aja ya?, kalo diliat desain figmanya bgitu :v

**Comment by itsMallix** [comment]
<img src="https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/328e80d7-889d-4ef0-a48f-315f69cdf557" width="30%"> <img src="https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/8f25049b-7eeb-428b-8069-ae47556031c6" width="30%"> <img src="https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/1c0732c1-9c78-4c2f-9fe8-b33eb0354526" width="30%">

Mau tanya juga, ini data lat sama long dari anak be emang gitu ta? atau nanti bakal diupdate?, soalnya lokasinya random banget atau aku yang salah :v

yang di laut = itu pakai parameter latlong dari response api yang passing param buat nge pin markernya
![Image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/9ff95587-890a-419f-995a-405f2e74ae09)

yang di inggris = itu pakai latlong user saat ini ditambah latlong dari warehousenya :v
![Image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/85415488/4b7824dc-a94c-42ce-920c-c9ceefd69aea)

**Comment by michaelis2101** [comment]
iyak emang gitu man, tim be buat longitude sama latitudenya itu masih input manual, jadi random lokasinya wkwkwk, soalnya di fe belum implementasi API jadi datanya semuanya masih bawaan tim be yang input manual itu :v

**Comment by itsMallix** [comment]
Owalahh mangkannyaa wqwq, berarti ini pakek latlong default dari response apinya aja yak
